# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standup_app', '0003_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=30)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='standup_app.Employee')),
            ],
        ),
    ]
